# Generated by Django 3.2.5 on 2021-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='myVotedIds',
            field=models.TextField(blank=True),
        ),
    ]
