# Generated by Django 3.2.5 on 2021-09-20 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 9, 20, 9, 46, 10, 332343), editable=False),
        ),
    ]
