# Generated by Django 3.2.5 on 2021-09-21 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_review_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 10, 33, 31, 567297)),
        ),
    ]
