# Generated by Django 3.2.5 on 2021-09-21 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_review_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 13, 59, 40, 493053)),
        ),
    ]
