# Generated by Django 3.2.5 on 2021-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=200)),
                ('imdbID', models.CharField(max_length=8)),
                ('textBody', models.CharField(max_length=500)),
                ('numRating', models.IntegerField()),
                ('upVotes', models.IntegerField()),
                ('downVotes', models.IntegerField()),
            ],
        ),
    ]
